<a href="https://colab.research.google.com/github/GuptaShivam007/Applied_Neural_Network_Manually/blob/main/Neural_Network_Manual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [ ]:
dataset=pd.read_csv('insurance_data.csv')

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(dataset[['age','affordibility']],dataset['bought_insurance'],test_size=0.2,random_state=0)

In [ ]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100
X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [ ]:
X_train_scaled

age  affordibility
24  0.50              1
13  0.29              0
20  0.21              1
25  0.54              1
16  0.25              0
1   0.25              0
10  0.18              1
27  0.46              1
26  0.23              1
8   0.62              1
6   0.55              0
4   0.46              1
18  0.19              0
19  0.18              1
9   0.61              1
7   0.60              0
23  0.45              1
3   0.52              0
0   0.22              1
21  0.26              0
15  0.55              1
12  0.27              0

In [ ]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.fit(X_train_scaled,y_train,epochs=5000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 10ms/step - loss: 0.5396 - accuracy: 0.8636
Epoch 2502/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5396 - accuracy: 0.8636
Epoch 2503/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5395 - accuracy: 0.8636
Epoch 2504/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5395 - accuracy: 0.8636
Epoch 2505/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5395 - accuracy: 0.8636
Epoch 2506/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5394 - accuracy: 0.8636
Epoch 2507/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.5394 - accuracy: 0.8636
Epoch 2508/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.5393 - accuracy: 0.8636
Epoch 2509/5000
1/1 [==============================] - 0s 13ms/step - loss: 0.5393 - accuracy: 0.8636
Epoch 2510/5000
1/1 [============================

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def log_loss(y_true,y_pred):
  epsilon=1e-15
  y_pred_new=[max(i,epsilon) for i in y_pred]
  y_pred_new=[min(i, 1-epsilon) for i in y_pred_new]
  y_pred_new=np.array(y_pred_new)
  return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [ ]:
class myNN():
  def __init__(self):
    self.w1=1
    self.w2=1
    self.bias=0
  def fit(self,X,y_true,epochs,threshold):
    self.w1,self.w2,self.bias=self.gradient_descent(X['age'],X['affordibility'],y_true,epochs,threshold)
  def predict(self,X_test):
    weighted_sum=self.w1*X_test['age']+self.w2*X_test['affordibility']+self.bias
    return sigmoid(weighted_sum)
  def gradient_descent(self,age,affordibility,y_true,epochs,threshold):
    w1=1
    w2=1
    bias=0
    rate=0.5
    n=len(age)
    for i in range(epochs):
      weight=w1*age+w2*affordibility+bias
      y_pred=sigmoid(weight)
      loss=log_loss(y_true,y_pred)
      w1d=(1/n)*np.dot(np.transpose(age),(y_pred-y_true))
      w2d=(1/n)*np.dot(np.transpose(affordibility),(y_pred-y_true))
      bias_d=np.mean(y_pred-y_true)
      w1=w1-rate*w1d
      w2=w2-rate*w2d
      bias=bias-rate*bias_d
      print(f'epochs:{i}, w1:{w1}, w2:{w2}, loss:{loss}, bias:{bias}')
      if(loss<=threshold):
        break
    return w1,w2,bias

In [ ]:
custom=myNN()
custom.fit(X_train_scaled,y_train,5000,0.4662)

epochs:0, w1:0.9644915668168719, w2:0.9224250019701856, loss:0.7960362503355486, bias:-0.1521744437835525
epochs:1, w1:0.9366743363654499, w2:0.8570969777186894, loss:0.7394293670708099, bias:-0.2838815971644586
epochs:2, w1:0.9160190930945575, w2:0.8035200242324965, loss:0.6980698848391689, bias:-0.39666489545168215
epochs:3, w1:0.9017701861063158, w2:0.7606695089288332, loss:0.6686193819406211, bias:-0.4926120466423785
epochs:4, w1:0.8930731543176171, w2:0.7272344982483193, loss:0.6479960845015644, bias:-0.5740228037875161
epochs:5, w1:0.8890759364765383, w2:0.7018265973050505, loss:0.6336578618954344, bias:-0.6431543649176596
epochs:6, w1:0.8889918350364353, w2:0.6831195783238424, loss:0.6236667598398874, bias:-0.7020686534913516
epochs:7, w1:0.8921292648124783, w2:0.6699231996615576, loss:0.6166236529551378, bias:-0.7525646139800298
epochs:8, w1:0.8978991061148434, w2:0.6612102292494013, loss:0.6115548071590622, bias:-0.796166156177148
epochs:9, w1:0.9058095436860382, w2:0.65611589

In [ ]:
coef,intercept=model.get_weights()
coef,intercept

(array([[4.298625 ],
        [1.2754214]], dtype=float32),
 array([-2.831575], dtype=float32))

In [ ]:
model.predict(X_train_scaled)

1/1 [==============================] - 0s 19ms/step


array([[0.64408964],
       [0.17009223],
       [0.34221426],
       [0.68246084],
       [0.14717668],
       [0.14717668],
       [0.31380263],
       [0.6037738 ],
       [0.36182085],
       [0.75194156],
       [0.3852481 ],
       [0.6037738 ],
       [0.11765397],
       [0.31380263],
       [0.743837  ],
       [0.4372329 ],
       [0.5934456 ],
       [0.35519293],
       [0.35195518],
       [0.15265433],
       [0.69170237],
       [0.15829808]], dtype=float32)

In [ ]:
custom.predict(X_train_scaled)

24    0.643960
13    0.183769
20    0.339385
25    0.682698
16    0.159142
1     0.159142
10    0.310831
27    0.603241
26    0.359109
8     0.752763
6     0.410332
4     0.603241
18    0.127302
19    0.310831
9     0.744598
7     0.463667
23    0.592809
3     0.379235
0     0.349183
21    0.165036
15    0.692024
12    0.171104
dtype: float64